# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/steve/Desktop/MyCPU/MyCPU.cache/wt [current_project]
set_property parent.project_path C:/Users/steve/Desktop/MyCPU/MyCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/steve/Desktop/MyCPU/MyCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/divider.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/cu.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/cu_contrl.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/alu_contrl.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/alu.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/mdr.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/mar.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/sp.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/regarray.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/pc.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/instreg.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/flags.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/clock.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/disp.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/display.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/rom.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/ram.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/addr_decode.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/risc_cpu.v
  C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/sources_1/new/cpu_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/constrs_1/new/cpu_cons.xdc
set_property used_in_implementation false [get_files C:/Users/steve/Desktop/MyCPU/MyCPU.srcs/constrs_1/new/cpu_cons.xdc]


synth_design -top cpu_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef cpu_top.dcp

catch { report_utilization -file cpu_top_utilization_synth.rpt -pb cpu_top_utilization_synth.pb }
